In [ ]:
import pandas as pd

books = pd.read_csv("../dataset/books_genre.csv")
books["content_features"] = books["content_features"].fillna("")
books["content_features"] = books["content_features"].astype(str)
print(books["content_features"].isnull().sum())

0

In [91]:
from sklearn.feature_extraction.text import TfidfVectorizer



tfidf = TfidfVectorizer( stop_words = "english" , max_features = 5000)


tfidf_matrix = tfidf.fit_transform(books["content_features"])
print(tfidf_matrix.shape)

(9818, 5000)

In [92]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_simi = cosine_similarity(tfidf_matrix, tfidf_matrix)
print(cosine_simi.shape)

(9818, 9818)

In [93]:
def recommend_book(title, topn = 10):

    title = title.lower()
    
    books["title_clean"] = books["title"].fillna("").str.lower()

    matches = books[books["title_clean"].str.contains(title)]
    if matches.empty:
        return "Book not found"
    
    index = matches.index[0]
    simi_scores = list(enumerate(cosine_simi[index]))
    simi_scores = sorted(simi_scores, key=lambda x: x[1] , reverse=True )
    simi_scores = simi_scores[1:topn+1]
    indices = [i[0] for i in simi_scores]

    return books.iloc[indices][["title","authors","tag_name"]]

In [143]:
recommend_book("atonement")

,title,authors,tag_name
570,everything is illuminated,Jonathan Safran Foer,to-read fiction favorites historical-fiction b...
110,catch22,Joseph Heller,to-read currently-reading classics fiction fav...
541,the virgin suicides,Jeffrey Eugenides,to-read favorites fiction currently-reading yo...
6433,the good soldier,"Ford Madox Ford, Kenneth Womack, William Baker",to-read fiction classics currently-reading fav...
804,a room with a view,E.M. Forster,to-read classics fiction favorites romance cla...
1043,vanity fair,"William Makepeace Thackeray, John Carey",to-read classics currently-reading fiction cla...
5317,small island,Andrea Levy,to-read fiction currently-reading historical-f...
1643,lady chatterleys lover,"D.H. Lawrence, Doris Lessing, Chester Brown",classics to-read romance classic owned books-i...
1399,sophies choice,William Styron,to-read currently-reading fiction classics his...
2353,a passage to india,"E.M. Forster, Oliver Stallybrass, Pankaj Mishra",to-read classics currently-reading fiction ind...

In [95]:
books["title"].head(20)

0                   the hunger games the hunger games 1
1     harry potter and the sorcerers stone harry pot...
2                                   twilight twilight 1
3                                 to kill a mockingbird
4                                      the great gatsby
5                                the fault in our stars
6                                            the hobbit
7                                the catcher in the rye
8                      angels  demons  robert langdon 1
9                                   pride and prejudice
10                                      the kite runner
11                                divergent divergent 1
12                                                 1984
13                                          animal farm
14                            the diary of a young girl
15         the girl with the dragon tattoo millennium 1
16                     catching fire the hunger games 2
17    harry potter and the prisoner of azkaban harry...
18    the fellowship of the ring the lord of the rin...
19                        mockingjay the hunger games 3
Name: title, dtype: object

In [99]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

cosin_simi = cosine_similarity(tfidf_matrix, tfidf_matrix)

In [100]:
def hybrid_recommender(user_id, book_title, topn = 5):

    book_title = book_title.lower()
    books["title_clean"] = books["title"].str.lower()
    
    matches = books[books["title_clean"].str.contains(book_title, na=False)]

    if matches.empty:
        return "Book not found"

    index = matches.index[0] 
    simi_scores = list(enumerate(cosine_simi[index]))
    simi_scores = sorted(simi_scores, key=lambda x: x[1], reverse=True)
    recommendations = []

    for i , score in simi_scores:
        book_id = books.iloc[i]["book_id"]
        svd_score = svd_model.predict(user_id, book_id).est
        final_score = 0.6 * svd_score + 0.4 * score
        recommendations.append((books.iloc[i]["title"], final_score))

    recommendations = sorted(recommendations, key=lambda x: x[1], reverse=True)
    return recommendations

In [101]:
hybrid_recommender(user_id=1, book_title="Jane")

[('amsterdam', 2.8778603193221364),
 ('the curious incident of the dog in the nighttime', 2.8426855481245923),
 ('women in love brangwen family 2', 2.8390464645058118),
 ('hard times', 2.8271686831743184),
 ('tears of the giraffe no 1 ladies detective agency 2', 2.8264560909017757),
 ('still life with woodpecker', 2.808189184538185),
 ('girl with a pearl earring', 2.7978796104247965),
 ('villa incognito', 2.7764029875280016),
 ('peter and the shadow thieves peter and the starcatchers 2',
  2.7757730859952434),
 ('love in the time of cholera', 2.768282410405617),
 ('the taste of home cookbook', 2.7655347239564625),
 ('the beautiful and damned', 2.756070643816708),
 ('madame bovary', 2.7537126258118443),
 ('on beauty', 2.73364104918651),
 ('of mice and men', 2.728315157643904),
 ('atlas shrugged', 2.7282616006052507),
 ('treasure island', 2.72709564735362),
 ('a peoples history of the united states', 2.724481530363071),
 ('franny and zooey', 2.721899716585522),
 ('cane river', 2.7104374784425307),
 ('three men in a boat three men 1', 2.7088911425480937),
 ('consider the lobster and other essays', 2.704794368631906),
 ('the rules of attraction', 2.70319408239389),
 ('harry potter and the order of the phoenix harry potter 5',
  2.7019067899227487),
 ('atonement', 2.696181565497674),
 ('deception point', 2.6925225173291585),
 ('beloved', 2.691515519711281),
 ('the secret garden', 2.685805821215748),
 ('four blondes', 2.6844428984672937),
 ('carter beats the devil', 2.6818597488905684),
 ('little house in the big woods little house 1', 2.67902785010265),
 ('mariel of redwall redwall 4', 2.6718921593986464),
 ('going solo', 2.670547407045146),
 ('men are from mars women are from venus', 2.6700603243567245),
 ('jane eyre', 2.6682338250555735),
 ('harry potter and the halfblood prince harry potter 6', 2.6671901280898487),
 ('tropic of capricorn', 2.665893812968732),
 ('the adventures of huckleberry finn', 2.663788594327981),
 ('great expectations', 2.660746782292717),
 ('sickened the memoir of a munchausen by proxy childhood',
  2.6595745726308095),
 ('longitude the true story of a lone genius who solved the greatest scientific problem of his time',
  2.659560490158145),
 ('the pilgrimage', 2.6558819729543557),
 ('the salmon of doubt dirk gently 3', 2.653387363667495),
 ('lost horizon', 2.652593185431674),
 ('the heart of the matter', 2.6506374107798534),
 ('the brooklyn follies', 2.64756208828751),
 ('hocus pocus', 2.6468791788057473),
 ('the hitchhikers guide to the galaxy hitchhikers guide to the galaxy 1',
  2.640900373024478),
 ('the bell jar', 2.63907116726837),
 ('special topics in calamity physics', 2.6374773180278352),
 ('neither here nor there travels in europe', 2.63542981820634),
 ('kafka on the shore', 2.6347687828718827),
 ('the time machine', 2.634613132073287),
 ('blindness', 2.629056212340675),
 ('wuthering heights', 2.6263604307708586),
 ('the winter of our discontent', 2.6258961206773597),
 ('the world according to garp', 2.624531056364566),
 ('the androids dream', 2.622275647740574),
 ('the complete sherlock holmes vol 2', 2.6217761002727835),
 ('fullmetal alchemist vol 1 fullmetal alchemist 1', 2.616619552646542),
 ('sex and the city', 2.616586947967233),
 ('pale fire', 2.6156465351109315),
 ('the quiet american', 2.614895278933734),
 ('deadeye dick', 2.613462237946853),
 ('the adventures of sherlock holmes', 2.6130203440773174),
 ('the lost boy dave pelzer 2', 2.6125459841047163),
 ('plum lovin stephanie plum 125', 2.61209400223006),
 ('the blank slate the modern denial of human nature', 2.6099324770608976),
 ('first they killed my father a daughter of cambodia remembers',
  2.609006141516245),
 ('brave new world revisited', 2.6077861337304653),
 ('infinite jest', 2.6069230832753965),
 ('the millionaire next door the surprising secrets of americas wealthy',
  2.606294480604283),
 ('heidi', 2.600808120068867),
 ('fear and loathing in las vegas', 2.599722186810423),
 ('martin chuzzlewit', 2.598319816956333),
 ('a house for mr biswas', 2.5958870084143855),
 ('animal farm', 2.593854678788156),
 ('a bend in the road', 2.591819984814513),
 ('prophet', 2.5914192850052054),
 ('fahrenheit 451', 2.5913810831971293),
 ('about a boy', 2.5884901706870473),
 ('maurice', 2.588007173714756),
 ('dispatches', 2.5869525683063244),
 ('the atonement child', 2.5865525868961967),
 ('charlie and the chocolate factory charlie bucket 1', 2.5860402301375944),
 ('harry potter collection harry potter 16', 2.5849960912637844),
 ('another roadside attraction', 2.581309779095302),
 ('villette', 2.5750952775785607),
 ('the vampires assistant cirque du freak 2', 2.574615777954573),
 ('the book of ruth', 2.5737373516677886),
 ('the war of the worlds', 2.571937665045454),
 ('the last juror', 2.5704193536552538),
 ('jurassic park jurassic park 1', 2.5682443737645966),
 ('howards end', 2.564482398909238),
 ('the baron in the trees', 2.562857957362605),
 ('a fine balance', 2.5626822359659758),
 ('the legend of luke redwall 12', 2.5616281761244935),
 ('shirley', 2.5613444640302556),
 ('lipstick jungle', 2.5611380230035397),
 ('the valkyries', 2.5604786755235085),
 ('deerskin', 2.5603018012003878),
 ('the woman in the dunes', 2.559649234955951),
 ('the universe in a nutshell', 2.557605858903517),
 ('the tenant of wildfell hall', 2.557457176105673),
 ('dirk gentlys holistic detective agency dirk gently 1', 2.5570353599881304),
 ('la dame aux camlias', 2.5570000095601344),
 ('the design of everyday things', 2.556957982173622),
 ('daniel deronda', 2.556549677358301),
 ('in a sunburned country', 2.554173823653778),
 ('memoirs of a geisha', 2.5536168040475142),
 ('into thin air a personal account of the mount everest disaster',
  2.552938511598725),
 ('assassination vacation', 2.55218860501521),
 ('one hundred years of solitude', 2.5509883810061513),
 ('memories of my melancholy whores', 2.550468764630243),
 ('harry potter and the prisoner of azkaban harry potter 3',
  2.5495538637704445),
 ('number9dream', 2.5488296150673917),
 ('the comfort of strangers', 2.5484067693866663),
 ('superman birthright', 2.5483957618621127),
 ('the long walk', 2.547464266542665),
 ('burmese days', 2.546891917398365),
 ('the bookseller of kabul', 2.5467638670016806),
 ('one for the money stephanie plum 1', 2.545550355298208),
 ('harry potter and the goblet of fire harry potter 4', 2.5447705614742246),
 ('glamorama', 2.5438002668392583),
 ('the emperors children', 2.5430810796125507),
 ('agnes grey', 2.5428878737426586),
 ('the brethren', 2.5424901253580945),
 ('a heartbreaking work of staggering genius', 2.5410196420183304),
 ('the rescue', 2.5409154837328987),
 ('welcome to the monkey house', 2.539226306723847),
 ('falling angels', 2.5390594351632214),
 ('the power of now a guide to spiritual enlightenment', 2.5378034461586227),
 ('a woman of substance emma harte saga 1', 2.5370944363435575),
 ('complete works of oscar wilde', 2.53696354398048),
 ('sense and sensibility', 2.536178621781922),
 ('survival in auschwitz', 2.5347130339946147),
 ('the shadow of the wind the cemetery of forgotten books  1',
  2.534432936167041),
 ('so long and thanks for all the fish hitchhikers guide to the galaxy 4',
  2.5309070691628994),
 ('keep the aspidistra flying', 2.5297199853135868),
 ('the broken wings', 2.529616542555666),
 ('the good earth house of earth 1', 2.528004910715798),
 ('i hope they serve beer in hell tucker max 1', 2.527235022598277),
 ('last chance saloon', 2.5271873131628975),
 ('olympos ilium 2', 2.525015875663539),
 ('the smoke jumper', 2.5245641417149227),
 ('the hobbit', 2.524097642355052),
 ('fierce invalids home from hot climates', 2.5228765197831495),
 ('the brothers karamazov', 2.5227361484712176),
 ('the 158pound marriage', 2.521793410141663),
 ('his excellency george washington', 2.521591396021054),
 ('next', 2.5208202819762446),
 ('the amber room', 2.5207578234202273),
 ('the professor', 2.519602444221749),
 ('north and south', 2.5193959549338305),
 ('life and times of michael k', 2.5189304156670094),
 ('mansfield park', 2.5184710159370987),
 ('high five stephanie plum 5', 2.5179540413195687),
 ('anne frank beyond the diary  a photographic remembrance', 2.51724766938272),
 ('cry the beloved country', 2.516319438585015),
 ('night the night trilogy 1', 2.5158287066740663),
 ('pride and prejudice', 2.515671351340765),
 ('silas marner', 2.515069073571916),
 ('morality for beautiful girls no 1 ladies detective agency 3',
  2.514777612520791),
 ('forever in blue the fourth summer of the sisterhood sisterhood 4',
  2.5138883794620224),
 ('lord of the flies', 2.5120268242048502),
 ('city of glass the new york trilogy 1', 2.511956649242101),
 ('holy cow an indian adventure', 2.5107537632766275),
 ('dreamland', 2.5104985759327603),
 ('mans search for meaning', 2.509076631543732),
 ('northanger abbey', 2.508590879472699),
 ('pygmalion', 2.5081756918313602),
 ('the known world', 2.508120246667544),
 ('angels  demons  robert langdon 1', 2.506126076643627),
 ('the restaurant at the end of the universe hitchhikers guide 2',
  2.5026015844853045),
 ('middlesex', 2.501769367225698),
 ('frankenstein', 2.501581649032381),
 ('we were the mulvaneys', 2.500780143431059),
 ('middlemarch', 2.498379592038097),
 ('the bellmaker redwall 7', 2.498365442011961),
 ('slaughterhousefive', 2.4980072831269844),
 ('digging to america', 2.49794469831503),
 ('i am charlotte simmons', 2.4971360871813526),
 ('the history of love', 2.496399715275703),
 ('the corrections', 2.495635566964672),
 ('the hungry tide', 2.495571622966447),
 ('herzog', 2.4950374196759473),
 ('the old man and the sea', 2.494719584099949),
 ('casino royale james bond 1', 2.4946345983241023),
 ('reservation blues', 2.494500035635299),
 ('bagombo snuff box', 2.494258141529393),
 ('rebecca', 2.494206746699434),
 ('the long winter little house 6', 2.4941476629868777),
 ('player piano', 2.4939764021532733),
 ('suffer the children', 2.4938482251534504),
 ('the awakening', 2.4936991993555124),
 ('the way the crow flies', 2.492295491441116),
 ('the lover', 2.4922175725176676),
 ('the ultimate hitchhikers guide to the galaxy', 2.49183033963535),
 ('the call of the wild', 2.4916838084390736),
 ('the mill on the floss', 2.491597959324976),
 ('rachels holiday walsh family 2', 2.491262632522807),
 ('the waves', 2.491067569905928),
 ('god bless you mr rosewater', 2.490862195189357),
 ('oliver twist', 2.4901679056647055),
 ('demons', 2.4901196629615314),
 ('generation x tales for an accelerated culture', 2.4898504753380104),
 ('the physician cole family trilogy 1', 2.489693556321719),
 ('dracula', 2.489379249017308),
 ('life of pi', 2.4874551479358975),
 ('the mayor of casterbridge', 2.486827318610485),
 ('blue ocean strategy how to create uncontested market space and make the competition irrelevant',
  2.486443302110896),
 ('persepolis volume 1', 2.4862289016267423),
 ('tess of the durbervilles', 2.4858025981656566),
 ('the andromeda strain', 2.485398795457768),
 ('a home at the end of the world', 2.4852583490044813),
 ('little altars everywhere', 2.484927939299128),
 ('the game penetrating the secret society of pickup artists',
  2.484786594404513),
 ('the woodlanders', 2.483734938202199),
 ('embroideries', 2.4827587889817946),
 ('1776', 2.4826609296943527),
 ('five little peppers and how they grew', 2.4825637924291013),
 ('the french lieutenants woman', 2.481644882046615),
 ('a painted house', 2.4812020497164204),
 ('orlando', 2.481030765804877),
 ('howl and other poems', 2.4808496022836293),
 ('the return of the native', 2.48061948904597),
 ('the scarlet letter', 2.4803126107113735),
 ('hatchet brians saga 1', 2.478535128075783),
 ('breakfast at tiffanys', 2.4783093819943103),
 ('adam bede', 2.4776030373775177),
 ('shopaholic  baby shopaholic 5', 2.477119494731847),
 ('marlfox redwall 11', 2.476998318215837),
 ('the red pony', 2.47689880095901),
 ('mrs dalloway', 2.4767740230297814),
 ('play it as it lays', 2.4765045441621307),
 ('mother night', 2.476027346770578),
 ('the yellow wallpaper', 2.4758973169745495),
 ('the collector', 2.4757750666848857),
 ('shopaholic and sister shopaholic 4', 2.475763284678916),
 ('the invisible man', 2.4754861267126183),
 ('their eyes were watching god', 2.474996374835793),
 ('dont make me think a common sense approach to web usability',
  2.4749816961634847),
 ('the deep end of the ocean cappadora family 1', 2.474870741951737),
 ('mary barton', 2.4745218998411618),
 ('the power and the glory', 2.474348911222925),
 ('brighton rock', 2.4743342544129243),
 ('cranford', 2.4738848858700995),
 ('night over water', 2.4735954035725554),
 ('what i loved', 2.473542629366232),
 ('bel canto', 2.472947843036507),
 ('the turn of the screw', 2.4728523682815267),
 ('david copperfield', 2.4725361954832485),
 ('kurt vonneguts cats cradle modern critical interpretations',
  2.47226172452091),
 ('the house of the seven gables', 2.4721978816773063),
 ('the island of dr moreau', 2.471964074699282),
 ('the witches', 2.471616147813647),
 ('uncle toms cabin', 2.471556716470004),
 ('hard eight stephanie plum 8', 2.4709829414164868),
 ('one flew over the cuckoos nest', 2.470789345500759),
 ('nicholas nickleby', 2.4706470484939587),
 ('wide sargasso sea', 2.4699623303497793),
 ('lucy sullivan is getting married', 2.4698876567221597),
 ('timeline', 2.4694026339949118),
 ('the last of the mohicans the leatherstocking tales 2', 2.4688745242562478),
 ('on love', 2.468299625491538),
 ('to the lighthouse', 2.468001027404137),
 ('the end of the affair', 2.4679498357175156),
 ('the yellow wallpaper and other stories', 2.4670607884683657),
 ('american gods american gods 1', 2.466905605605561),
 ('i capture the castle', 2.4666037230595728),
 ('far from the madding crowd', 2.4658745340521886),
 ('sputnik sweetheart', 2.4654426833226046),
 ('all the kings men', 2.465206030391568),
 ('mobydick or the whale', 2.4651692060600428),
 ('bleak house', 2.4651131036113063),
 ('a short history of tractors in ukrainian', 2.4644168203401318),
 ('qed the strange theory of light and matter', 2.464114908109284),
 ('lady chatterleys lover', 2.464024098905799),
 ('message in a bottle', 2.463826166086632),
 ('the virgin suicides', 2.4638250797360204),
 ('kidnapped david balfour 1', 2.4635504657473173),
 ('what to expect the first year what to expect', 2.4623117669538015),
 ('oranges are not the only fruit', 2.4616808781351116),
 ('the strange case of dr jekyll and mr hyde', 2.4616522097735394),
 ('heart of darkness and the secret sharer', 2.460712274661634),
 ('shadow of the giant enders shadow 4', 2.460318328254451),
 ('jude the obscure', 2.4602812556465867),
 ('the secret history', 2.460115323842045),
 ('pygmalion  my fair lady', 2.4591710314024553),
 ('a map of the world', 2.4590016519753375),
 ('catch22', 2.4587882023148),
 ('fingersmith', 2.4581824347543315),
 ('haroun and the sea of stories khalifa brothers 1', 2.4575633042285254),
 ('martin eden', 2.4568159260557785),
 ('last orders', 2.4565200449332063),
 ('sexing the cherry', 2.456481291315106),
 ('goldfinger james bond 7', 2.456422664328049),
 ('in cold blood', 2.4563277753142483),
 ('song of susannah the dark tower 6', 2.4562160471239816),
 ('the bonfire of the vanities', 2.456153274225529),
 ('the rainmaker', 2.456143900684101),
 ('the pit and the pendulum', 2.4552541261838035),
 ('written on the body', 2.4548487558643903),
 ('from russia with love james bond 5', 2.454776757477594),
 ('the buddha of suburbia', 2.454440385695409),
 ('less than zero', 2.454436174756309),
 ('the prime of miss jean brodie', 2.454007029716189),
 ('the three musketeers', 2.453990092042128),
 ('the rainbow', 2.4539209654998984),
 ('skipping christmas', 2.4535589596958385),
 ('the forsyte saga the forsyte chronicles 13', 2.4534913496153825),
 ('dragonfly in amber outlander 2', 2.4534888707678824),
 ('the importance of being earnest', 2.4534825232021964),
 ('anne frank remembered the story of the woman who helped to hide the frank family',
  2.4532025353967177),
 ('sons and lovers', 2.4531051405056847),
 ('rainbow six jack ryan universe 10', 2.4529827567459472),
 ('a history of the world in 6 glasses', 2.452611263801905),
 ('the big sleep philip marlowe 1', 2.4526023262720646),
 ('my ntonia', 2.4525212570660004),
 ('bluebeard', 2.452371645172575),
 ('a clockwork orange', 2.4519237032986414),
 ('the house of mirth', 2.4518981359828667),
 ('passing', 2.4518387654369),
 ('king solomons mines allan quatermain 1', 2.4515749324483687),
 ('wise blood', 2.4515141097618898),
 ('lady audleys secret', 2.4512045601462686),
 ('the terminal man', 2.4506037742876647),
 ('the passion', 2.450186423246805),
 ('a history of god the 4000year quest of judaism christianity and islam',
  2.450017361376738),
 ('children of dune dune chronicles 3', 2.4499811908745737),
 ('papillon', 2.4495597738103996),
 ('the hunchback of notredame', 2.4488178173643433),
 ('the fall of the house of usher', 2.448814970793362),
 ('through the lookingglass and what alice found there', 2.448809246192627),
 ('times arrow', 2.448298427378468),
 ('white teeth', 2.4482773569681857),
 ('delta of venus', 2.4480926024031064),
 ('cloud atlas', 2.4480574299982822),
 ('walden', 2.4478546147876648),
 ('the grapes of wrath', 2.44762473652773),
 ('the crying of lot 49', 2.4475641764990503),
 ('the jungle', 2.447435619003411),
 ('a gate at the stairs', 2.4471513210205753),
 ('job a comedy of justice', 2.4469393008117706),
 ('everything is illuminated', 2.446827289560162),
 ('jewel', 2.4466946038073583),
 ('a tree grows in brooklyn', 2.4466660572065675),
 ('surfacing', 2.4462685278133542),
 ('jamaica inn', 2.4461639153086217),
 ('brideshead revisited the sacred and profane memories of captain charles ryder',
  2.4457226929496714),
 ('oblivion', 2.44491452511841),
 ('the great gatsby', 2.4444373537426087),
 ('we the living', 2.4440419972431684),
 ('the awakening and selected stories', 2.4437059954790614),
 ('brave new world', 2.4436780889850924),
 ('brokeback mountain', 2.443555404965881),
 ('breath eyes memory', 2.443472211143219),
 ('heretics of dune dune chronicles 5', 2.443459601645849),
 ('the scarlet pimpernel', 2.44296372047253),
 ('drop city', 2.442863638682583),
 ('all quiet on the western front', 2.4427093789702634),
 ('the count of monte cristo', 2.442701289479504),
 ('the midwich cuckoos', 2.4425958255800584),
 ('team of rivals the political genius of abraham lincoln',
  2.4424174596235098),
 ('the book of illusions', 2.442329810851373),
 ('built to last successful habits of visionary companies',
  2.4423201844168405),
 ('under the skin', 2.442308142504727),
 ('the art of fielding', 2.4417771638264334),
 ('the 39 steps richard hannay 1', 2.4415694340432115),
 ('regeneration regeneration 1', 2.441482389248755),
 ('home gilead 2', 2.4410931616700733),
 ('in watermelon sugar', 2.4410664437559495),
 ('the moonstone', 2.4410099259039697),
 ('the autograph man', 2.4409323705611525),
 ('endymion hyperion cantos 3', 2.440865747792664),
 ('lucky jim', 2.43987415551213),
 ('trials of death cirque du freak 5', 2.439550920851275),
 ('the age of innocence', 2.438912119414964),
 ('tender is the night', 2.4388866431699125),
 ('the robber bride', 2.438848931776244),
 ('alice in wonderland', 2.438644884788512),
 ('fear and loathing on the campaign trail 72', 2.438410853574298),
 ('the crow road', 2.4382083219239608),
 ('the glass castle', 2.4381878463635536),
 ('when god was a rabbit', 2.4380214287776267),
 ('the moors last sigh', 2.4380138394305026),
 ('lorna doone', 2.4378873650251434),
 ('cats eye', 2.4376799920240058),
 ('our mutual friend', 2.437672201640127),
 ('lord jim', 2.4372007628743515),
 ('redwall redwall 1', 2.436825649671349),
 ('sometimes a great notion', 2.43680162146559),
 ('the tipping point how little things can make a big difference',
  2.436363752674722),
 ('cold comfort farm', 2.435818230819424),
 ('alias grace', 2.4353407730231424),
 ('the once and future king the once and future king 14', 2.4352462768017733),

In [102]:
import joblib

joblib.dump(tfidf, "../backend/models/tfidf_vectorizer.pkl")
joblib.dump(cosine_simi, "../backend/models/cosine_sim.pkl")

['../backend/models/cosine_sim.pkl']

In [108]:
books["popularity"] = books["average_rating"] * books["ratings_count"]

trending_books = books.sort_values(by= "popularity" , ascending=False).head(20)
trending_books[["title", "authors", "average_rating", "ratings_count"]]

,title,authors,average_rating,ratings_count
0,the hunger games the hunger games 1,Suzanne Collins,4.34,4780653
1,harry potter and the sorcerers stone harry pot...,"J.K. Rowling, Mary GrandPré",4.44,4602479
2,twilight twilight 1,Stephenie Meyer,3.57,3866839
3,to kill a mockingbird,Harper Lee,4.25,3198671
4,the great gatsby,F. Scott Fitzgerald,3.89,2683664
5,the fault in our stars,John Green,4.26,2346404
6,the hobbit,J.R.R. Tolkien,4.25,2071616
9,pride and prejudice,Jane Austen,4.24,2035490
17,harry potter and the prisoner of azkaban harry...,"J.K. Rowling, Mary GrandPré, Rufus Beck",4.53,1832823
12,1984,"George Orwell, Erich Fromm, Celâl Üster",4.14,1956832
14,the diary of a young girl,"Anne Frank, Eleanor Roosevelt, B.M. Mooyaart-D...",4.10,1972666
11,divergent divergent 1,Veronica Roth,4.24,1903563
24,harry potter and the deathly hallows harry pot...,"J.K. Rowling, Mary GrandPré",4.61,1746574
23,harry potter and the goblet of fire harry pott...,"J.K. Rowling, Mary GrandPré",4.53,1753043
16,catching fire the hunger games 2,Suzanne Collins,4.30,1831039
22,harry potter and the chamber of secrets harry ...,"J.K. Rowling, Mary GrandPré",4.37,1779331
7,the catcher in the rye,J.D. Salinger,3.79,2044241
20,harry potter and the order of the phoenix harr...,"J.K. Rowling, Mary GrandPré",4.46,1735368
10,the kite runner,Khaled Hosseini,4.26,1813044
8,angels demons robert langdon 1,Dan Brown,3.85,2001311

In [129]:
def recommend_by_description(query, top_n=10):
    query_vec = tfidf.transform([query])
    sim_scores = cosine_similarity(query_vec, tfidf_matrix)
    
    scores = list(enumerate(sim_scores[0]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)
    
    book_indices = [i[0] for i in scores[:top_n]]
    
    return books.iloc[book_indices][["title", "authors", "tag_name"]]

In [139]:
recommend_by_description("A sad love story book")
recommend_by_description("fantasy book about children and animals")

,title,authors,tag_name
6167,wildwood wildwood chronicles 1,"Colin Meloy, Carson Ellis",to-read currently-reading fantasy young-adult ...
7779,the akhenaten adventure children of the lamp 1,P.B. Kerr,to-read fantasy young-adult currently-reading ...
8107,five children and it five children 1,E. Nesbit,to-read fantasy currently-reading classics chi...
6074,charmed life chrestomanci 1,Diana Wynne Jones,fantasy young-adult favorites ya fiction child...
8273,babar the king,Jean de Brunhoff,to-read childrens children children-s picture-...
467,the amber spyglass his dark materials 3,Philip Pullman,to-read fantasy young-adult favorites fiction ...
6949,the lives of christopher chant chrestomanci 2,Diana Wynne Jones,fantasy favorites to-read ya fiction childrens...
359,the subtle knife his dark materials 2,Philip Pullman,fantasy young-adult favorites to-read fiction ...
60,the golden compass his dark materials 1,Philip Pullman,to-read fantasy favorites young-adult currentl...
6360,the dark hills divide the land of elyon 1,Patrick Carman,fantasy to-read currently-reading favorites yo...

In [136]:
def recommend_by_genre(genre, topn=10):
    filter = books[books["tag_name"].str.contains(genre, case=False, na=False)]
    return filter.sort_values(by="ratings_count",ascending=False).head(topn)[["title","authors","tag_name"]]

In [144]:
recommend_by_genre("romance comedy")

,title,authors,tag_name
105,confessions of a shopaholic shopaholic 1,Sophie Kinsella,to-read favorites sophie-kinsella chic-lit fun...
616,ive got your number,Sophie Kinsella,to-read chicklit contemporary-romance funny re...
915,wallbanger cocktail 1,Alice Clayton,favorites currently-reading to-read contempora...
1093,2 states the story of my marriage,Chetan Bhagat,romance favorites indian-authors chetan-bhagat...
5330,second helpings jessica darling 2,Megan McCafferty,to-read young-adult favorites ya chick-lit fic...
7374,mars volume 01,Fuyumi Soryo,to-read manga romance favorites graphic-novels...
6456,yu yu hakusho volume 1 goodbye material world ...,Yoshihiro Togashi,to-read manga favorites fantasy graphic-novels...
6614,vinegar girl,Anne Tyler,to-read currently-reading fiction romance cont...
9551,millennium snow vol 1,Bisco Hatori,to-read manga romance vampires fantasy current...
9736,trouble in mudbug ghostinlaw 1,Jana Deleon,to-read currently-reading mystery kindle roman...

In [155]:
def recommend_by_author(name, topn=15):
    filter = books[books["authors"].str.contains(name, case=False, na=False)]
    return filter.sort_values(by="ratings_count", ascending=False).head(topn)[["title","authors"]]

In [158]:
recommend_by_author("agatha christie")

,title,authors
195,and then there were none,Agatha Christie
653,murder on the orient express hercule poirot 10,Agatha Christie
652,the mysterious affair at styles hercule poirot 1,"Agatha Christie, Ροζίτα Σώκου"
1028,murder at the vicarage miss marple 1,Agatha Christie
1374,the murder of roger ackroyd hercule poirot 4,Agatha Christie
1703,death on the nile hercule poirot 17,Agatha Christie
1694,the man in the brown suit,Agatha Christie
2189,the abc murders hercule poirot 13,Agatha Christie
3171,the body in the library miss marple 3,Agatha Christie
4160,evil under the sun hercule poirot 23,Agatha Christie
4634,a murder is announced miss marple 5,Agatha Christie
4940,450 from paddington miss marple 8,Agatha Christie
5556,murder in mesopotamia hercule poirot 14,Agatha Christie
5750,appointment with death hercule poirot 19,Agatha Christie
5014,the secret adversary tommy and tuppence 1,Agatha Christie